name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install frontend dependencies
        run: cd frontend && yarn install

      - name: Build frontend
        run: cd frontend && yarn vite build

      - name: Install backend dependencies
        run: cd backend && yarn install

      - name: Generate Prisma Client
        run: cd backend && npx prisma generate

      - name: Build backend
        run: cd backend && tsc

      - name: Create .nojekyll file
        run: touch frontend/dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./dist
