name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd backend && npm install
          cd ../frontend && npm install
          cd ../frontend && npm install react-router-dom
          cd ../frontend && npm install vite

      - name: Build backend and frontend
        run: |
          npm run build --prefix backend
          cd frontend && npx tsc && npx vite build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: frontend/build
